language: generic
addons:
  apt:
    packages:
      - "python3"
      - "python3-pip"
before_install:
  - wget -O- http://neuro.debian.net/lists/xenial.us-ca.full | sudo tee /etc/apt/sources.list.d/neurodebian.sources.list
  - sudo apt-key adv --recv-keys --keyserver hkp://pool.sks-keyservers.net:80 0xA5D32F012649A5A9
  - sudo apt-get update
  - sudo apt-get install -y singularity-container
  - pip3 install mint-cli
